# Generated by Django 5.2.5 on 2025-08-27 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=False)),
                ('appointment_reminders', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('am', 'አማርኛ'), ('or', 'Oromiffa')], default='en', max_length=2)),
                ('date_format', models.CharField(choices=[('gregorian', 'Gregorian'), ('ethiopian', 'Ethiopian')], default='gregorian', max_length=10)),
                ('timezone', models.CharField(default='Africa/Addis_Ababa', max_length=50)),
                ('session_timeout', models.IntegerField(choices=[(30, '30 minutes'), (60, '1 hour'), (120, '2 hours'), (240, '4 hours')], default=60)),
                ('additional_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
