# Generated by Django 5.2.5 on 2025-08-16 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('kebele', models.CharField(help_text='Kebele (local administrative unit)', max_length=100)),
                ('woreda', models.CharField(help_text='Woreda (district)', max_length=100)),
                ('city', models.CharField(default='Addis Ababa', max_length=100)),
                ('region', models.CharField(default='Addis Ababa', max_length=100)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+251912345678' or '0912345678'.", regex='^\\+?251?[0-9]{9,10}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+251912345678' or '0912345678'.", regex='^\\+?251?[0-9]{9,10}$')])),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('medical_history', models.TextField(blank=True, help_text='Previous medical conditions, surgeries, etc.')),
                ('allergies', models.TextField(blank=True, help_text='Known allergies')),
                ('current_medications', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
