# Generated by Django 5.2.5 on 2025-08-16 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('specialty', models.CharField(choices=[('general', 'General Medicine'), ('pediatrics', 'Pediatrics'), ('surgery', 'Surgery'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('gynecology', 'Gynecology'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry'), ('radiology', 'Radiology'), ('anesthesiology', 'Anesthesiology'), ('emergency', 'Emergency Medicine'), ('internal', 'Internal Medicine'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose, Throat)')], max_length=20)),
                ('sub_specialty', models.CharField(blank=True, max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('medical_school', models.CharField(max_length=200)),
                ('graduation_year', models.PositiveIntegerField()),
                ('certifications', models.TextField(blank=True, help_text='Additional certifications and qualifications')),
                ('consultation_fee', models.DecimalField(decimal_places=2, help_text='Fee in ETB', max_digits=10)),
                ('availability_status', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('on_call', 'On Call'), ('consultant', 'Consultant')], default='full_time', max_length=20)),
                ('monday_start', models.TimeField(blank=True, null=True)),
                ('monday_end', models.TimeField(blank=True, null=True)),
                ('tuesday_start', models.TimeField(blank=True, null=True)),
                ('tuesday_end', models.TimeField(blank=True, null=True)),
                ('wednesday_start', models.TimeField(blank=True, null=True)),
                ('wednesday_end', models.TimeField(blank=True, null=True)),
                ('thursday_start', models.TimeField(blank=True, null=True)),
                ('thursday_end', models.TimeField(blank=True, null=True)),
                ('friday_start', models.TimeField(blank=True, null=True)),
                ('friday_end', models.TimeField(blank=True, null=True)),
                ('saturday_start', models.TimeField(blank=True, null=True)),
                ('saturday_end', models.TimeField(blank=True, null=True)),
                ('sunday_start', models.TimeField(blank=True, null=True)),
                ('sunday_end', models.TimeField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, help_text="Doctor's biography for public display")),
                ('languages_spoken', models.CharField(default='Amharic, English', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
